rename nerscRoot to dockerRoot in torque files

diff --git a/dockerRoot/torque/nerscRoot-prologue b/dockerRoot/torque/nerscRoot-prologue
--- a/dockerRoot/torque/nerscRoot-prologue
+++ b/dockerRoot/torque/nerscRoot-prologue
@@ -13,8 +13,8 @@ CCM_JOBID=$1
 CCM_JID=`echo $CCM_JOBID | awk -F. '{print $1}'`
 CCM_USER=$2
 CCM_GROUP=$3
-NERSC_ROOT_TYPE=$4
-NERSC_ROOT_VALUE=$5
+DOCKER_ROOT_TYPE=$4
+DOCKER_ROOT_VALUE=$5
 
 CCM_APID_TIMEOUT=15
 
@@ -25,7 +25,7 @@ CCM_QUEUES="ccm_queue"
 LLMLOGGER="/opt/cray/llm/default/bin/xtlog"
 LLMCONF="/etc/opt/cray/llm/llm.conf"
 
-nerscRootSetupPath=/global/syscom/sc/nsg/opt/nerscRoot
+dockerRootSetupPath=@@@PREFIX@@@
 exit_code=0
 
 # Set apstat -n output columns
@@ -34,21 +34,21 @@ export apstat_nodeTable="NID,Arch,State,HW,Rv,Pl,PgSz,Avl,Conf,Placed,PEs,Apids"
 PATH=${PATH}:/opt/cray/alps/default/bin/
 
 
-echo "Initializing NERSC Root environment, Please Wait"
-if [ "x$NERSC_ROOT_TYPE" == "xDOCKER" ]; then
+echo "Initializing DockerRoot environment, Please Wait"
+if [ "x$DOCKER_ROOT_TYPE" == "xDOCKER" ]; then
     echo "Retrieving Docker Image"
-    echo $nerscRootSetupPath/getDockerImage.pl $NERSC_ROOT_VALUE
-    image=$( $nerscRootSetupPath/getDockerImage.pl $NERSC_ROOT_VALUE )
-    if [ "x$image" == "x" -o "x$image" == "xERR" ]; then
-        echo "Failed to get docker image: $NERSC_ROOT_VALUE"
+    image=$( $dockerRootSetupPath/bin/getDockerImage.pl -quiet $DOCKER_ROOT_VALUE )
+    ret=$?
+    if [ "x$image" == "x" -o $ret -ne 0 ]; then
+        echo "Failed to get docker image: $DOCKER_ROOT_VALUE"
+        exit 1
     else
-        NERSC_ROOT_VALUE=$image
+        DOCKER_ROOT_VALUE=$image
     fi
-    echo "got image $NERSC_ROOT_VALUE"
 fi
 
         if [ -z "$CCM_BATCH_RUNDIR" ] ; then
-            ccm_rundir=/var/run/crayccm_nerscroot
+            ccm_rundir=/var/run/crayccm_dockerroot
         else
             ccm_rundir=$CCM_BATCH_RUNDIR 
         fi
@@ -205,8 +205,8 @@ fi
         #
 #msg_severity=6 ; msg_type="ccm_prologue_mark"
 #        echo "${CCM_JOBID} `/bin/date +%c`" 2>&1 | logmsg
-        echo $xtxqtcmd_path $ccm_init_nodelist $nerscRootSetupPath/setupRoot.sh \"$NERSC_ROOT_TYPE\" \"$NERSC_ROOT_VALUE\"
-        $xtxqtcmd_path $ccm_init_nodelist "$nerscRootSetupPath/setupRoot.sh \"$NERSC_ROOT_TYPE\" \"$NERSC_ROOT_VALUE\"" >> $ccm_init_log 2>&1
+        echo $xtxqtcmd_path $ccm_init_nodelist $dockerRootSetupPath/sbin/setupRoot.sh \"$DOCKER_ROOT_TYPE\" \"$DOCKER_ROOT_VALUE\"
+        $xtxqtcmd_path $ccm_init_nodelist "$dockerRootSetupPath/sbin/setupRoot.sh \"$DOCKER_ROOT_TYPE\" \"$DOCKER_ROOT_VALUE\"" >> $ccm_init_log 2>&1
         okcnt=`grep "(complete)" $ccm_init_log | wc -l`
 
 #        CCM_PATH=/var/crayccm
@@ -225,11 +225,11 @@ fi
         echo $expcnt > $ccm_rundir/$CCM_USER/$CCM_JOBID.run
 
         if [ "$expcnt" == "$okcnt" ]; then
-                echo NerscRoot Start success, $okcnt of $expcnt responses
+                echo DockerRoot Start success, $okcnt of $expcnt responses
 #rm -f $ccm_init_log
                 exit_code=0
         else
-                echo NerscRoot Start failed, $okcnt of $expcnt responses
+                echo DockerRoot Start failed, $okcnt of $expcnt responses
                 echo Log on $ccm_init_log
                 chmod 644 $ccm_init_log
                 exit_code=1
